CREATE TABLE TPCH_SF1000.[_STAGING_CUSTOMER]
(
	[C_CUSTKEY] DECIMAL(38,0) NULL,
	[C_NAME] [varchar](25) NULL,
	[C_ADDRESS] [varchar](40) NULL,
	[C_NATIONKEY] DECIMAL(38,0) NULL,
	[C_PHONE] [varchar](15) NULL,
	[C_ACCTBAL] [decimal](12, 2) NULL,
	[C_MKTSEGMENT] [varchar](10) NULL,
	[C_COMMENT] [varchar](117) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE TPCH_SF1000.[CUSTOMER]
(
	[C_CUSTKEY] BIGINT NULL,
	[C_NAME] [varchar](25) NULL,
	[C_ADDRESS] [varchar](40) NULL,
	[C_NATIONKEY] BIGINT NULL,
	[C_PHONE] [varchar](15) NULL,
	[C_ACCTBAL] [decimal](12, 2) NULL,
	[C_MKTSEGMENT] [varchar](10) NULL,
	[C_COMMENT] [varchar](117) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)