CREATE TABLE TPCH_SF1000._STAGING_LINEITEM
(
	[L_ORDERKEY] DECIMAL(38,0) NULL,
	[L_PARTKEY] DECIMAL(38,0) NULL,
	[L_SUPPKEY] DECIMAL(38,0) NULL,
	[L_LINENUMBER] DECIMAL(38,0) NULL,
	[L_QUANTITY] [decimal](12, 2) NULL,
	[L_EXTENDEDPRICE] [decimal](12, 2) NULL,
	[L_DISCOUNT] [decimal](12, 2) NULL,
	[L_TAX] [decimal](12, 2) NULL,
	[L_RETURNFLAG] [CHAR](1) NULL,
	[L_LINESTATUS] [CHAR](1) NULL,
	[L_SHIPDATE] [date] NULL,
	[L_COMMITDATE] [date] NULL,
	[L_RECEIPTDATE] [date] NULL,
	[L_SHIPINSTRUCT] [varchar](25) NULL,
	[L_SHIPMODE] [varchar](10) NULL,
	[L_COMMENT] [varchar](44) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)


GO
CREATE TABLE TPCH_SF1000.LINEITEM
(
	[L_ORDERKEY] BIGINT NULL,
	[L_PARTKEY] BIGINT NULL,
	[L_SUPPKEY] BIGINT NULL,
	[L_LINENUMBER] BIGINT NULL,
	[L_QUANTITY] [decimal](12, 2) NULL,
	[L_EXTENDEDPRICE] [decimal](12, 2) NULL,
	[L_DISCOUNT] [decimal](12, 2) NULL,
	[L_TAX] [decimal](12, 2) NULL,
	[L_RETURNFLAG] [CHAR](1) NULL,
	[L_LINESTATUS] [CHAR](1) NULL,
	[L_SHIPDATE] [date] NULL,
	[L_COMMITDATE] [date] NULL,
	[L_RECEIPTDATE] [date] NULL,
	[L_SHIPINSTRUCT] [varchar](25) NULL,
	[L_SHIPMODE] [varchar](10) NULL,
	[L_COMMENT] [varchar](44) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


