
CREATE TABLE TPCH_SF1000.[_STAGING_NATION]
(
	[N_NATIONKEY] DECIMAL(38,0) NULL,
	[N_NAME] VARCHAR(25) NULL,
	[N_REGIONKEY] DECIMAL(38,0) NULL,
	[N_COMMENT] [varchar](152) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)



GO

CREATE TABLE TPCH_SF1000.[NATION]
(
	[N_NATIONKEY] BIGINT NULL,
	[N_NAME] VARCHAR(25) NULL,
	[N_REGIONKEY] BIGINT NULL,
	[N_COMMENT] [varchar](152) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)



