CREATE TABLE TPCH_SF1000._STAGING_PARTSUPP
(
	[PS_PARTKEY] DECIMAL(38,0) NULL,
	[PS_SUPPKEY] DECIMAL(38,0) NULL,
	[PS_AVAILQTY] DECIMAL(38,0) NULL,
	[PS_SUPPLYCOST] [decimal](12, 2) NULL,
	[PS_COMMENT] [varchar](199) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE TPCH_SF1000.PARTSUPP
(
	[PS_PARTKEY] BIGINT NULL,
	[PS_SUPPKEY] BIGINT NULL,
	[PS_AVAILQTY] BIGINT NULL,
	[PS_SUPPLYCOST] [decimal](12, 2) NULL,
	[PS_COMMENT] [varchar](199) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


