CREATE TABLE TPCH_SF1000.[_STAGING_PART]
(
	[P_PARTKEY] DECIMAL(38,0) NULL,
	[P_NAME] [varchar](55) NULL,
	[P_MFGR] [varchar](25) NULL,
	[P_BRAND] [varchar](10) NULL,
	[P_TYPE] [varchar](25) NULL,
	[P_SIZE] DECIMAL(38,0) NULL,
	[P_CONTAINER] [varchar](10) NULL,
	[P_RETAILPRICE] [decimal](12, 2) NULL,
	[P_COMMENT] [varchar](23) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO



GO
CREATE TABLE TPCH_SF1000.[PART]
(
	[P_PARTKEY] BIGINT NULL,
	[P_NAME] [varchar](55) NULL,
	[P_MFGR] [varchar](25) NULL,
	[P_BRAND] [varchar](10) NULL,
	[P_TYPE] [varchar](25) NULL,
	[P_SIZE] BIGINT NULL,
	[P_CONTAINER] [varchar](10) NULL,
	[P_RETAILPRICE] [decimal](12, 2) NULL,
	[P_COMMENT] [varchar](23) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


