CREATE TABLE [TPCH_SF1000].[_STAGING_SUPPLIER]
(
	[S_SUPPKEY] DECIMAL(38,0) NULL,
	[S_NAME] [varchar](25) NULL,
	[S_ADDRESS] [varchar](40) NULL,
	[S_NATIONKEY] DECIMAL(38,0) NULL,
	[S_PHONE] [varchar](15) NULL,
	[S_ACCTBAL] [decimal](12, 2) NULL,
	[S_COMMENT] [varchar](101) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE [TPCH_SF1000].[SUPPLIER]
(
	[S_SUPPKEY] [bigint] NULL,
	[S_NAME] [varchar](25) NULL,
	[S_ADDRESS] [varchar](40) NULL,
	[S_NATIONKEY] [bigint] NULL,
	[S_PHONE] [varchar](15) NULL,
	[S_ACCTBAL] [decimal](12, 2) NULL,
	[S_COMMENT] [varchar](101) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)