
TRUNCATE TABLE [TPCH_SF1000].[CUSTOMER]
TRUNCATE TABLE [TPCH_SF1000].[LINEITEM]
TRUNCATE TABLE [TPCH_SF1000].[NATION]
TRUNCATE TABLE [TPCH_SF1000].[ORDERS]
TRUNCATE TABLE [TPCH_SF1000].[PART]
TRUNCATE TABLE [TPCH_SF1000].[PARTSUPP]
TRUNCATE TABLE [TPCH_SF1000].[REGION]
TRUNCATE TABLE [TPCH_SF1000].[SUPPLIER]


INSERT INTO [TPCH_SF1000]._STAGING_CUSTOMER  SELECT * FROM [TPCH_SF1000].[CUSTOMER]
INSERT INTO [TPCH_SF1000]._STAGING_LINEITEM  SELECT * FROM [TPCH_SF1000].[LINEITEM]
INSERT INTO [TPCH_SF1000]._STAGING_NATION    SELECT * FROM [TPCH_SF1000].[NATION]
INSERT INTO [TPCH_SF1000]._STAGING_ORDERS    SELECT * FROM [TPCH_SF1000].[ORDERS]
INSERT INTO [TPCH_SF1000]._STAGING_PART      SELECT * FROM [TPCH_SF1000].[PART]
INSERT INTO [TPCH_SF1000]._STAGING_PARTSUPP  SELECT * FROM [TPCH_SF1000].[PARTSUPP]
INSERT INTO [TPCH_SF1000]._STAGING_REGION    SELECT * FROM [TPCH_SF1000].[REGION]
INSERT INTO [TPCH_SF1000]._STAGING_SUPPLIER  SELECT * FROM [TPCH_SF1000].[SUPPLIER]
