-- DW 3000
-- Run this in User DB

--SELECT name, is_auto_create_stats_on FROM sys.databases
--ALTER DATABASE  tpch2 SET AUTO_CREATE_STATISTICS ON

IF OBJECT_ID('[TPCH_SF1000].[CUSTOMER]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[CUSTOMER]
IF OBJECT_ID('[TPCH_SF1000].[LINEITEM]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[LINEITEM]
IF OBJECT_ID('[TPCH_SF1000].[NATION]')   IS NOT NULL   DROP TABLE  [TPCH_SF1000].[NATION]
IF OBJECT_ID('[TPCH_SF1000].[ORDERS]')   IS NOT NULL   DROP TABLE  [TPCH_SF1000].[ORDERS]
IF OBJECT_ID('[TPCH_SF1000].[PART]')     IS NOT NULL   DROP TABLE  [TPCH_SF1000].[PART]
IF OBJECT_ID('[TPCH_SF1000].[PARTSUPP]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[PARTSUPP]
IF OBJECT_ID('[TPCH_SF1000].[REGION]')   IS NOT NULL   DROP TABLE  [TPCH_SF1000].[REGION]
IF OBJECT_ID('[TPCH_SF1000].[SUPPLIER]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[SUPPLIER]


IF OBJECT_ID('[TPCH_SF1000].[_STAGING_CUSTOMER]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_CUSTOMER]
IF OBJECT_ID('[TPCH_SF1000].[_STAGING_LINEITEM]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_LINEITEM]
IF OBJECT_ID('[TPCH_SF1000].[_STAGING_NATION]')   IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_NATION]
IF OBJECT_ID('[TPCH_SF1000].[_STAGING_ORDERS]')   IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_ORDERS]
IF OBJECT_ID('[TPCH_SF1000].[_STAGING_PART]')     IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_PART]
IF OBJECT_ID('[TPCH_SF1000].[_STAGING_PARTSUPP]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_PARTSUPP]
IF OBJECT_ID('[TPCH_SF1000].[_STAGING_REGION]')   IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_REGION]
IF OBJECT_ID('[TPCH_SF1000].[_STAGING_SUPPLIER]') IS NOT NULL   DROP TABLE  [TPCH_SF1000].[_STAGING_SUPPLIER]

IF EXISTS (SELECT * FROM  sys.schemas WHERE name = 'TPCH_SF1000')  DROP SCHEMA TPCH_SF1000

IF EXISTS (SELECT * FROM  sys.sysusers where name = 'etlloaduser01') DROP USER etlloaduser01

GO
CREATE USER  etlloaduser01  WITHOUT LOGIN
EXEC sp_addrolemember 'db_owner', 'etlloaduser01'
EXEC sp_addrolemember 'xlargerc',  'etlloaduser01'
GO



CREATE SCHEMA [TPCH_SF1000]
GO
CREATE TABLE [TPCH_SF1000].[_STAGING_CUSTOMER]
(
	[C_CUSTKEY] DECIMAL(38,0) NULL,
	[C_NAME] [varchar](25) NULL,
	[C_ADDRESS] [varchar](40) NULL,
	[C_NATIONKEY] DECIMAL(38,0) NULL,
	[C_PHONE] [varchar](15) NULL,
	[C_ACCTBAL] [decimal](12, 2) NULL,
	[C_MKTSEGMENT] [varchar](10) NULL,
	[C_COMMENT] [varchar](117) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE [TPCH_SF1000].[CUSTOMER]
(
	[C_CUSTKEY] BIGINT NULL,
	[C_NAME] [varchar](25) NULL,
	[C_ADDRESS] [varchar](40) NULL,
	[C_NATIONKEY] BIGINT NULL,
	[C_PHONE] [varchar](15) NULL,
	[C_ACCTBAL] [decimal](12, 2) NULL,
	[C_MKTSEGMENT] [varchar](10) NULL,
	[C_COMMENT] [varchar](117) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE [TPCH_SF1000].[_STAGING_LINEITEM]
(
	[L_ORDERKEY] DECIMAL(38,0) NULL,
	[L_PARTKEY] DECIMAL(38,0) NULL,
	[L_SUPPKEY] DECIMAL(38,0) NULL,
	[L_LINENUMBER] DECIMAL(38,0) NULL,
	[L_QUANTITY] [decimal](12, 2) NULL,
	[L_EXTENDEDPRICE] [decimal](12, 2) NULL,
	[L_DISCOUNT] [decimal](12, 2) NULL,
	[L_TAX] [decimal](12, 2) NULL,
	[L_RETURNFLAG] [CHAR](1) NULL,
	[L_LINESTATUS] [CHAR](1) NULL,
	[L_SHIPDATE] [date] NULL,
	[L_COMMITDATE] [date] NULL,
	[L_RECEIPTDATE] [date] NULL,
	[L_SHIPINSTRUCT] [varchar](25) NULL,
	[L_SHIPMODE] [varchar](10) NULL,
	[L_COMMENT] [varchar](44) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)


GO
CREATE TABLE [TPCH_SF1000].[LINEITEM]
(
	[L_ORDERKEY] BIGINT NULL,
	[L_PARTKEY] BIGINT NULL,
	[L_SUPPKEY] BIGINT NULL,
	[L_LINENUMBER] BIGINT NULL,
	[L_QUANTITY] [decimal](12, 2) NULL,
	[L_EXTENDEDPRICE] [decimal](12, 2) NULL,
	[L_DISCOUNT] [decimal](12, 2) NULL,
	[L_TAX] [decimal](12, 2) NULL,
	[L_RETURNFLAG] [CHAR](1) NULL,
	[L_LINESTATUS] [CHAR](1) NULL,
	[L_SHIPDATE] [date] NULL,
	[L_COMMITDATE] [date] NULL,
	[L_RECEIPTDATE] [date] NULL,
	[L_SHIPINSTRUCT] [varchar](25) NULL,
	[L_SHIPMODE] [varchar](10) NULL,
	[L_COMMENT] [varchar](44) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO



CREATE TABLE [TPCH_SF1000].[_STAGING_NATION]
(
	[N_NATIONKEY] DECIMAL(38,0) NULL,
	[N_NAME] VARCHAR(25) NULL,
	[N_REGIONKEY] DECIMAL(38,0) NULL,
	[N_COMMENT] [varchar](152) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)



GO

CREATE TABLE [TPCH_SF1000].[NATION]
(
	[N_NATIONKEY] BIGINT NULL,
	[N_NAME] VARCHAR(25) NULL,
	[N_REGIONKEY] BIGINT NULL,
	[N_COMMENT] [varchar](152) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)



CREATE TABLE [TPCH_SF1000].[_STAGING_ORDERS]
(
	[O_ORDERKEY] DECIMAL(38,0) NULL,
	[O_CUSTKEY] DECIMAL(38,0) NULL,
	[O_ORDERSTATUS] CHAR(1) NULL,
	[O_TOTALPRICE] [decimal](12, 2) NULL,
	[O_ORDERDATE] [date] NULL,
	[O_ORDERPRIORITY] [varchar](15) NULL,
	[O_CLERK] [varchar](15) NULL,
	[O_SHIPPRIORITY] DECIMAL(38,0) NULL,
	[O_COMMENT] [varchar](79) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE [TPCH_SF1000].[ORDERS]
(
	[O_ORDERKEY] BIGINT NULL,
	[O_CUSTKEY] BIGINT NULL,
	[O_ORDERSTATUS] CHAR(1) NULL,
	[O_TOTALPRICE] [decimal](12, 2) NULL,
	[O_ORDERDATE] [date] NULL,
	[O_ORDERPRIORITY] [varchar](15) NULL,
	[O_CLERK] [varchar](15) NULL,
	[O_SHIPPRIORITY] BIGINT NULL,
	[O_COMMENT] [varchar](79) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)

CREATE TABLE [TPCH_SF1000].[_STAGING_PART]
(
	[P_PARTKEY] DECIMAL(38,0) NULL,
	[P_NAME] [varchar](55) NULL,
	[P_MFGR] [varchar](25) NULL,
	[P_BRAND] [varchar](10) NULL,
	[P_TYPE] [varchar](25) NULL,
	[P_SIZE] DECIMAL(38,0) NULL,
	[P_CONTAINER] [varchar](10) NULL,
	[P_RETAILPRICE] [decimal](12, 2) NULL,
	[P_COMMENT] [varchar](23) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO



GO
CREATE TABLE [TPCH_SF1000].[PART]
(
	[P_PARTKEY] BIGINT NULL,
	[P_NAME] [varchar](55) NULL,
	[P_MFGR] [varchar](25) NULL,
	[P_BRAND] [varchar](10) NULL,
	[P_TYPE] [varchar](25) NULL,
	[P_SIZE] BIGINT NULL,
	[P_CONTAINER] [varchar](10) NULL,
	[P_RETAILPRICE] [decimal](12, 2) NULL,
	[P_COMMENT] [varchar](23) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


CREATE TABLE [TPCH_SF1000].[_STAGING_PARTSUPP]
(
	[PS_PARTKEY] DECIMAL(38,0) NULL,
	[PS_SUPPKEY] DECIMAL(38,0) NULL,
	[PS_AVAILQTY] DECIMAL(38,0) NULL,
	[PS_SUPPLYCOST] [decimal](12, 2) NULL,
	[PS_COMMENT] [varchar](199) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE [TPCH_SF1000].[PARTSUPP]
(
	[PS_PARTKEY] BIGINT NULL,
	[PS_SUPPKEY] BIGINT NULL,
	[PS_AVAILQTY] BIGINT NULL,
	[PS_SUPPLYCOST] [decimal](12, 2) NULL,
	[PS_COMMENT] [varchar](199) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO



CREATE TABLE [TPCH_SF1000].[_STAGING_REGION]
(
	[R_REGIONKEY] DECIMAL(38,0) NULL,
	[R_NAME] [varchar](25) NULL,
	[R_COMMENT] [varchar](152) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)



GO
CREATE TABLE [TPCH_SF1000].[REGION]
(
	[R_REGIONKEY] BIGINT NULL,
	[R_NAME] [varchar](25) NULL,
	[R_COMMENT] [varchar](152) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)



CREATE TABLE [TPCH_SF1000].[_STAGING_SUPPLIER]
(
	[S_SUPPKEY] DECIMAL(38,0) NULL,
	[S_NAME] [varchar](25) NULL,
	[S_ADDRESS] [varchar](40) NULL,
	[S_NATIONKEY] DECIMAL(38,0) NULL,
	[S_PHONE] [varchar](15) NULL,
	[S_ACCTBAL] [decimal](12, 2) NULL,
	[S_COMMENT] [varchar](101) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE [TPCH_SF1000].[SUPPLIER]
(
	[S_SUPPKEY] [bigint] NULL,
	[S_NAME] [varchar](25) NULL,
	[S_ADDRESS] [varchar](40) NULL,
	[S_NATIONKEY] [bigint] NULL,
	[S_PHONE] [varchar](15) NULL,
	[S_ACCTBAL] [decimal](12, 2) NULL,
	[S_COMMENT] [varchar](101) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)