CREATE TABLE TPCH_SF1000._STAGING_ORDERS
(
	[O_ORDERKEY] DECIMAL(38,0) NULL,
	[O_CUSTKEY] DECIMAL(38,0) NULL,
	[O_ORDERSTATUS] CHAR(1) NULL,
	[O_TOTALPRICE] [decimal](12, 2) NULL,
	[O_ORDERDATE] [date] NULL,
	[O_ORDERPRIORITY] [varchar](15) NULL,
	[O_CLERK] [varchar](15) NULL,
	[O_SHIPPRIORITY] DECIMAL(38,0) NULL,
	[O_COMMENT] [varchar](79) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
CREATE TABLE TPCH_SF1000.ORDERS
(
	[O_ORDERKEY] BIGINT NULL,
	[O_CUSTKEY] BIGINT NULL,
	[O_ORDERSTATUS] CHAR(1) NULL,
	[O_TOTALPRICE] [decimal](12, 2) NULL,
	[O_ORDERDATE] [date] NULL,
	[O_ORDERPRIORITY] [varchar](15) NULL,
	[O_CLERK] [varchar](15) NULL,
	[O_SHIPPRIORITY] BIGINT NULL,
	[O_COMMENT] [varchar](79) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)