-- User Master
CREATE LOGIN etlloaduser01 WITH password='PerfTest@2020';
CREATE USER etlloaduser01 FROM LOGIN etlloaduser01
GO
-- User DB
CREATE USER etlloaduser01 FROM LOGIN etlloaduser01
EXEC sp_addrolemember 'db_owner', 'etlloaduser01'
EXEC sp_addrolemember 'xlargerc',  'etlloaduser01'
GO
EXECUTE AS USER = 'etlloaduser01';
-- 1 minute to load
COPY INTO [TPCH_SF1000].[_STAGING_CUSTOMER]
(
C_CUSTKEY,
C_NAME,
C_ADDRESS,
C_NATIONKEY,
C_PHONE,
C_ACCTBAL,
C_MKTSEGMENT,
C_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/CUSTOMER/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')
	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
GO
--20 Mins and 38 seconds to load on DW 3000 / XLRC
COPY INTO [TPCH_SF1000].[_STAGING_LINEITEM]
(
L_ORDERKEY,
L_PARTKEY,
L_SUPPKEY,
L_LINENUMBER,
L_QUANTITY,
L_EXTENDEDPRICE,
L_DISCOUNT,
L_TAX,
L_RETURNFLAG,
L_LINESTATUS,
L_SHIPDATE,
L_COMMITDATE,
L_RECEIPTDATE,
L_SHIPINSTRUCT,
L_SHIPMODE,
L_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/LINEITEM/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')
	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
GO
EXECUTE AS USER = 'etlloaduser01';
COPY INTO [TPCH_SF1000]._STAGING_NATION
(
N_NATIONKEY,
N_NAME,
N_REGIONKEY,
N_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/NATION/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'	
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
GO
EXECUTE AS USER = 'etlloaduser01';
-- 3 mins and 32 seconds to load
COPY INTO [TPCH_SF1000]._STAGING_ORDERS
(
O_ORDERKEY,
O_CUSTKEY,
O_ORDERSTATUS,
O_TOTALPRICE,
O_ORDERDATE,
O_ORDERPRIORITY,
O_CLERK,
O_SHIPPRIORITY,
O_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/ORDERS/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')
	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
GO
-- 34 seconds to load
COPY INTO [TPCH_SF1000]._STAGING_PART
(
P_PARTKEY,
P_NAME,
P_MFGR,
P_BRAND,
P_TYPE,
P_SIZE,
P_CONTAINER,
P_RETAILPRICE,
P_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/PART/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')
	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
GO
-- 2 mins and 1 sec to load
COPY INTO [TPCH_SF1000]._STAGING_PARTSUPP
(
PS_PARTKEY,
PS_SUPPKEY,
PS_AVAILQTY,
PS_SUPPLYCOST,
PS_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/PARTSUPP/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
GO
-- 1 second to run
COPY INTO [TPCH_SF1000]._STAGING_REGION
(
R_REGIONKEY,
R_NAME,
R_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/REGION/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')
	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
GO

-- 8 seconds to run
COPY INTO [TPCH_SF1000]._STAGING_SUPPLIER
(
S_SUPPKEY,
S_NAME,
S_ADDRESS,
S_NATIONKEY,
S_PHONE,
S_ACCTBAL,
S_COMMENT
)
FROM 'https://tpchsf100.dfs.core.windows.net/tpchsf1000/SUPPLIER/*.parquet'
WITH
(
	FILE_TYPE = 'PARQUET'
	,CREDENTIAL=(IDENTITY= 'Storage Account Key', SECRET='ZBQcEvMbcj7ToOPYdTGhLmxCwBntOAXv5iKTvJG9YY97T0UxFzlC6RHyG62MDW+iGkI/6hheVckqibxsyLG4/A==')
	,MAXERRORS = 0
	,COMPRESSION = 'snappy'
	,IDENTITY_INSERT = 'OFF'
)
