EXECUTE AS USER = 'etlloaduser01';

DECLARE @Msg NVARCHAR(200)
SET @Msg = 'Truncating tables Started | ' + CAST(GETDATE() AS VARCHAR) 
RAISERROR (@Msg,10,1)       WITH  NOWAIT

TRUNCATE TABLE [TPCH_SF10000].[CUSTOMER]
TRUNCATE TABLE [TPCH_SF10000].[LINEITEM]
TRUNCATE TABLE [TPCH_SF10000].[NATION]
TRUNCATE TABLE [TPCH_SF10000].[ORDERS]
TRUNCATE TABLE [TPCH_SF10000].[PART]
TRUNCATE TABLE [TPCH_SF10000].[PARTSUPP]
TRUNCATE TABLE [TPCH_SF10000].[REGION]
TRUNCATE TABLE [TPCH_SF10000].[SUPPLIER]
SET @Msg = 'Truncating tables Completed | ' + CAST(GETDATE() AS VARCHAR) 
RAISERROR (@Msg,10,1)       WITH  NOWAIT

INSERT INTO [TPCH_SF10000].[CUSTOMER]  SELECT * FROM [TPCH_SF10000].[_STAGING_CUSTOMER]
INSERT INTO [TPCH_SF10000].[LINEITEM]  SELECT * FROM [TPCH_SF10000].[_STAGING_LINEITEM]
INSERT INTO [TPCH_SF10000].[NATION]    SELECT * FROM [TPCH_SF10000].[_STAGING_NATION]
INSERT INTO [TPCH_SF10000].[ORDERS]    SELECT * FROM [TPCH_SF10000].[_STAGING_ORDERS]
INSERT INTO [TPCH_SF10000].[PART]      SELECT * FROM [TPCH_SF10000].[_STAGING_PART]
INSERT INTO [TPCH_SF10000].[PARTSUPP]  SELECT * FROM [TPCH_SF10000].[_STAGING_PARTSUPP]
INSERT INTO [TPCH_SF10000].[REGION]    SELECT * FROM [TPCH_SF10000].[_STAGING_REGION]
INSERT INTO [TPCH_SF10000].[SUPPLIER]  SELECT * FROM [TPCH_SF10000].[_STAGING_SUPPLIER]

IF EXISTS (select * from sys.stats where name = 'stat_TPCHSF1000_CUSTOMER_CUSTKEY')
	BEGIN
		UPDATE STATISTICS [TPCH_SF10000].[CUSTOMER]		WITH FULLSCAN;
		UPDATE STATISTICS [TPCH_SF10000].[LINEITEM]		WITH FULLSCAN;
		UPDATE STATISTICS [TPCH_SF10000].[NATION]		WITH FULLSCAN;
		UPDATE STATISTICS [TPCH_SF10000].[ORDERS]		WITH FULLSCAN;
		UPDATE STATISTICS [TPCH_SF10000].[PART]			WITH FULLSCAN;
		UPDATE STATISTICS [TPCH_SF10000].[PARTSUPP]		WITH FULLSCAN;
		UPDATE STATISTICS [TPCH_SF10000].[REGION]		WITH FULLSCAN;
		UPDATE STATISTICS [TPCH_SF10000].[SUPPLIER]		WITH FULLSCAN;
	END
ELSE
	BEGIN
		CREATE STATISTICS [stat_TPCHSF1000_CUSTOMER_CUSTKEY]   ON [TPCH_SF10000].[CUSTOMER]([C_CUSTKEY])	WITH FULLSCAN;
		CREATE STATISTICS [stat_TPCHSF1000_CUSTOMER_NATIONKEY] ON [TPCH_SF10000].[CUSTOMER]([C_NATIONKEY])	WITH FULLSCAN;

		CREATE STATISTICS [stat_TPCHSF1000_LINEITEM_ORDERKEY]  ON [TPCH_SF10000].[LINEITEM]([L_ORDERKEY])	WITH FULLSCAN;
		CREATE STATISTICS [stat_TPCHSF1000_LINEITEM_PARTKEY]   ON [TPCH_SF10000].[LINEITEM]([L_PARTKEY])	WITH FULLSCAN;
		CREATE STATISTICS [stat_TPCHSF1000_LINEITEM_SUPPKEY]   ON [TPCH_SF10000].[LINEITEM]([L_SUPPKEY])	WITH FULLSCAN;

		CREATE STATISTICS [stat_TPCHSF1000_NATION_NATIONKEY]   ON [TPCH_SF10000].[NATION]([N_NATIONKEY])	WITH FULLSCAN;
		CREATE STATISTICS [stat_TPCHSF1000_NATION_REGIONKEY]   ON [TPCH_SF10000].[NATION]([N_REGIONKEY])	WITH FULLSCAN;

		CREATE STATISTICS [stat_TPCHSF1000_ORDERS_ORDERKEY]    ON [TPCH_SF10000].[ORDERS]([O_ORDERKEY])		WITH FULLSCAN;
		CREATE STATISTICS [stat_TPCHSF1000_ORDERS_CUSTKEY]     ON [TPCH_SF10000].[ORDERS]([O_CUSTKEY])		WITH FULLSCAN;

		CREATE STATISTICS [stat_TPCHSF1000_PART_PARTKEY]       ON [TPCH_SF10000].[PART]([P_PARTKEY])		WITH FULLSCAN;

		CREATE STATISTICS [stat_TPCHSF1000_PARTSUPP_PARTKEY]   ON [TPCH_SF10000].[PARTSUPP]([PS_PARTKEY])    WITH FULLSCAN;
		CREATE STATISTICS [stat_TPCHSF1000_PARTSUPP_SUPPKEY]   ON [TPCH_SF10000].[PARTSUPP]([PS_SUPPKEY])    WITH FULLSCAN;

		CREATE STATISTICS [stat_TPCHSF1000_REGION_REGIONKEY]   ON [TPCH_SF10000].[REGION]([R_REGIONKEY])		WITH FULLSCAN;

		CREATE STATISTICS [stat_TPCHSF1000_SUPPLIER_SUPPKEY]   ON [TPCH_SF10000].[SUPPLIER]([S_SUPPKEY])		WITH FULLSCAN;
		CREATE STATISTICS [stat_TPCHSF1000_SUPPLIER_NATIONKEY] ON [TPCH_SF10000].[SUPPLIER]([S_NATIONKEY])		WITH FULLSCAN;
	END
GO
DROP TABLE [TPCH_SF10000].[_STAGING_CUSTOMER]
DROP TABLE [TPCH_SF10000].[_STAGING_LINEITEM]
DROP TABLE [TPCH_SF10000].[_STAGING_NATION]
DROP TABLE [TPCH_SF10000].[_STAGING_ORDERS]
DROP TABLE [TPCH_SF10000].[_STAGING_PART]
DROP TABLE [TPCH_SF10000].[_STAGING_PARTSUPP]
DROP TABLE [TPCH_SF10000].[_STAGING_REGION]
DROP TABLE [TPCH_SF10000].[_STAGING_SUPPLIER]

GO
SELECT TableName,RowCount1,CAST((RowCount1/1000000.0) AS NUMERIC(12,2)) as Million_Rows FROM 
(
SELECT 'CUSTOMER' as TableName,COUNT_BIG(*) as RowCount1 FROM [TPCH_SF10000].[CUSTOMER]
UNION ALL
SELECT 'LINEITEM' as TableName,COUNT_BIG(*) as RowCount1 FROM [TPCH_SF10000].[LINEITEM]
UNION ALL
SELECT 'NATION' as TableName,COUNT_BIG(*) as RowCount1   FROM [TPCH_SF10000].[NATION]
UNION ALL
SELECT 'ORDERS' as TableName,COUNT_BIG(*) as RowCount1   FROM [TPCH_SF10000].[ORDERS]
UNION ALL
SELECT 'PART' as TableName,COUNT_BIG(*) as RowCount1     FROM [TPCH_SF10000].[PART]
UNION ALL
SELECT 'PARTSUPP' as TableName,COUNT_BIG(*) as RowCount1 FROM [TPCH_SF10000].[PARTSUPP]
UNION ALL
SELECT 'REGION' as TableName,COUNT_BIG(*) as RowCount1   FROM [TPCH_SF10000].[REGION]
UNION ALL
SELECT 'SUPPLIER' as TableName,COUNT_BIG(*) as RowCount1 FROM [TPCH_SF10000].[SUPPLIER]
) x

